Fix trust graph node click and max node issue
Tribler/tribler pull request #5863
Opened 2020-12-16 13:09 UTC by xoriole

- It fixes the crash on clicking a node in the Trust graph. The issue was because of reorganization of the arguments in pyqtsignal. The list of items where user clicked was splited to a single top point and a list of rest points. (Qt signal is magic).

- It fixes the crash occurring when there are nodes more than the max value. There was a test for that but the failure was suppressed as failure. The removal inheritance of unnecessary `TaskManager` fixes that apparently.

- The query parameter was removed in the last refactor. It is fixed now. A test is added as well. The refresh from the GUI should work nicely now.

Screenshot
![trust-graph-working](https://user-images.githubusercontent.com/1442867/102352565-315a7700-3fa8-11eb-8a43-d4f2631123f1.png)

2020-12-16 13:50 UTC, xoriole commented
retest this please

2020-12-17 14:52 UTC, drew2a requested changes

2020-12-17 14:52 UTC, drew2a commented on src/tribler-core/tribler_core/restapi/tests/test_trustview_endpoint.py
> +        # seq_num = random.randint(1, 100)
nit: this code comment can be safely removed :)

2020-12-18 11:42 UTC, xoriole commented
GUI test on macOS is failing because of https://github.com/Tribler/tribler/issues/5864 so keeping this PR on hold until the blocking issue is fixed.

2020-12-18 17:42 UTC, drew2a approved these changes

2020-12-19 16:44 UTC, merged