Fix #5867
Tribler/tribler pull request #5876
Opened 2020-12-22 13:33 UTC by drew2a

This PR fixes #5867 by removing `self.reset_view()` calling after clicking on a "search result breadcrumb".

This call was the cause of sending `TriblerNetworkRequest` with unexpected arguments.

2020-12-22 14:41 UTC, xoriole reviewed
This should fix the mentioned issue but I'm not sure about the impact of removing the else clause on other pages. ChannelContentsWidget is widely used (search_results_page, channel_contents_page, discovered_page). Maybe @ichorid can comment.

2020-12-22 19:11 UTC, ichorid requested changes
@xoriole is right.

Indeed, resetting the view on clicking the top/last breadcrumb is an important feature that allows to e.g. reset the list contents in case the user is lost in the list, or just wants to get the default sorting options.

The proper solution to this problem is to either fill the `filter` property from the "Search" lineEdit, or overload the `reset_view` for the `SearchModel` (IIRC).

2020-12-22 19:59 UTC, drew2a commented
@ichorid @xoriole you can check the PR. The logic to return to the previous page is kept. Only the ability to click on the rightmost (the last breadcrumb) item is removed.

Why we should reset the view on click at the rightmost item? It is counterintuitive. 

Anyway, @ichorid maybe it is better to reassign the issue to you, because it is your code, and you can provide a more correct solution.

2020-12-23 10:43 UTC, ichorid commented
> Why should we reset the view on click at the rightmost item? It is counterintuitive.

Because we don't have a "Refresh" :recycle:  button.

You're right, I'll better fix it myself.

2020-12-23 10:43 UTC, closed without merging

2020-12-23 11:03 UTC, drew2a commented
@ichorid reset and refresh are not the same things.

2020-12-23 11:30 UTC, ichorid commented
Yep. And we're not a browser. That's why we don't have a separate button to reset the page contents - because it is useless most of the time. But it is still sometimes necessary to reset the page, especially during development :wink: 

If you have a better idea of where to put it - welcome!

2020-12-23 12:00 UTC, drew2a commented
Not everything that is good for development is good for the user.

We can (and should) add some tools that will make our lives easier as developers. But these tools should not affect our users.

If you want to refresh the page it is ok to add this logic to the rightmost item in breadcrumbs ("current page" in the example below).

```
root page / child page / current page
```

If you want to reset the page it is ok to add this logic to the leftmost item in breadcrumbs (root page in the example above)