Recover from a corrupt config on startup
Tribler/tribler pull request #5912
Opened 2021-01-08 11:52 UTC by xoriole

If Tribler encounters a corrupted config file during startup, it should try to recover using the default config and inform the user about it. This is exactly what this PR does.

Fixes https://github.com/Tribler/tribler/issues/5548

2021-01-08 12:26 UTC, ichorid reviewed
The test config file should be full of binary zeroes, not just text `\00` :wink:

2021-01-08 13:53 UTC, drew2a commented
@xoriole probably you have to change the target branch to release-7.7 :)

2021-01-08 16:02 UTC, ichorid requested changes
The test config file is still not binary zeroes. That's ASCII zeroes.
![изображение](https://user-images.githubusercontent.com/2509103/104036115-4dca8780-51d3-11eb-9a91-99a33792c3a1.png)

2021-01-11 09:14 UTC, xoriole commented on src/run_tribler.py
> +        config = TriblerConfig(state_dir, config_file=state_dir / CONFIG_FILENAME, recover_error=True)
Done

2021-01-11 09:38 UTC, xoriole commented on src/tribler-core/tribler_core/config/test_tribler_config.py
> +
Done

2021-01-11 10:15 UTC, ichorid commented
:+1:

2021-01-11 10:16 UTC, ichorid approved these changes

2021-01-11 10:16 UTC, merged