Ignore patch version in upgrade scenarios
Tribler/tribler pull request #5933
Opened 2021-01-11 21:03 UTC by ichorid

*hopefully* fixes #5927 

There is a double check that should have prevented that scenario:
* the directory existence check
* the version check

This PR fixes the version check. Indeed, there was a problem (we did not ignore the patch number when considering if we should  upgrade the version.) Well, I still can't understand how the user pulled that off, 'cause the directory existence check seems to work (at least according to automated and manual tests). They could still trigger that if they manually deleted the directory during the upgrade procedure or something like that.

2021-01-12 09:53 UTC, drew2a commented
@ichorid release has been already published. Therefore, the target branch has to be changed.

2021-01-12 10:51 UTC, drew2a requested changes

2021-01-12 10:51 UTC, drew2a commented on src/tribler-core/tribler_core/upgrade/version_manager.py
> +           ((new_ver.version[0] == old_ver.version[0]) and (new_ver.version[1] > old_ver.version[1]))
**suggestion:** this version probably will be more reader-friendly:

```python
    major_version_is_greater = new_ver.version[0] > old_ver.version[0]
    major_version_is_equal = new_ver.version[0] == old_ver.version[0]
    minor_version_is_greater = new_ver.version[1] > old_ver.version[1]

    return major_version_is_greater or (major_version_is_equal and minor_version_is_greater)
```

2021-01-12 11:44 UTC, xoriole approved these changes

2021-01-12 11:50 UTC, ichorid commented
> @ichorid release has been already published. Therefore, the target branch has to be changed.

I thought we were probably going to do a patch release?

2021-01-15 16:54 UTC, drew2a approved these changes

2021-01-15 17:44 UTC, merged