WIP: Add a seeder
Tribler/tribler pull request #6077
Opened 2021-04-26 15:11 UTC by drew2a

This PR introduces scripts to easily set up a seedbox for propagating data to Tribler's network. 

Linked to https://github.com/Tribler/tribler/issues/21

The seedbox consists of two parts:

1. Torrent seeding (by using a LibTorrent protocol)
1. Channel disseminating (by using the Tribler network)

## Prerequisites

1. Clone the tribler repo include sub modules:
    ```shell
    git clone --recursive https://github.com/Tribler/tribler.git
    ```
1. Install requirements:
    ```bash
    python3 -m pip install -r requirements.txt 
    ```
1. Add necessary folders to `PYTHONPATH` (below the bash example)
    ```shell
    export PYTHONPATH=${PYTHONPATH}:`echo .. ../src/{pyipv8,tribler-common,tribler-core} | tr " " :`
    ```
   
## Torrent seeding

To start torrents' seeding run the following script:

```bash
python3 seeder.py <source folder>
```

Consider the following folder structure:

```
source folder
├ sub_directory
| ├ file1
| └file2
├ sub_directory2
| ├ file3
| └ file4
├ thumbnail.png
└ description.md
```

In this particular example, `seeder.py` will create two torrents:
`sub_directory.torrent` and `sub_directory2.torrent`.

`seeder.py` will start to seed them through BitTorrent protocol after creating.

## Data disseminating

To start disseminating data through Tribler's network run the following script:

```bash
python3 disseminator.py <source folder>
```

This script will create a channel and will disseminate it to Tribler.

Consider the following folder structure:

```
source folder
├ sub_directory.torrent
├ sub_directory2.torrent
├ thumbnail.png
└ description.md
```

Above you can see two "special" files:
* thumbnail.png
* description.md

The channel will be created with description based on these files. 
As the channel name, the source folder's name will be used.

### Error reporting

In case you want errors to be reported, you can use [Sentry](https://develop.sentry.dev/)

To enable error reporting, specify the following environment variable:

```bash
export SENTRY_URL=<sentry_url>
```

URL can be taken directly from a corresponding Sentry project.

### Generate test data

The following script generates `1GB` dataset divided into `1024` folders:

```shell
python3 generate_test_data.py -d /tmp/test_data  
```

2021-04-29 12:47 UTC, ichorid requested changes
Could you please move the `seeder` dir into either the `src` dir or `experiments` dir?

It is better to keep the toplevel structure of the project repository clean, if possible.

2021-04-29 18:33 UTC, drew2a commented
>Could you please move the seeder dir into either the src dir or experiments dir?

The seeder dir has been moved to `src`. As for my opinion, `src` is a bad place for scripts like 'seeder.

> It is better to keep the toplevel structure of the project repository clean, if possible.

Agree, but I don't see any "dirtying" in the original PR.

2021-05-03 16:51 UTC, ichorid submitted a review, later dismissed

2021-05-17 13:47 UTC, ichorid approved these changes

2021-05-17 14:57 UTC, merged