Don’t filter any groups of people out of existence
Tribler/tribler pull request #6259
Opened 2021-08-13 15:20 UTC by da2x

The 90s called. They want their discriminatory keyword filter list back.

Some searches that aren’t allowed with the current filter:

* belgian waffles
* asian tv, asian cousine, asuan culture
* scandianvian nature, scandinavian architecture
* gay interest (a common label for media with LGBTQ characters)
* turkish movies
* danish children tv (watch [John Dillermand](https://www.youtube.com/watch?v=A51mJjFyG_w))

I’ve removed the groups of people (but left in slurs) I could identify from the list. I was surprised that there were so many given names are on the list. I understand these may be adult performers, but blocking every artist or creator named Alexis, Charlie, or one of the hundred other names on the list is crazy. These should be removed as well, but let’s address those in a separate pr.

2021-08-14 06:04 UTC, qstokkink commented
ok to test

2021-08-15 07:59 UTC, ichorid commented
Originally, the filter was a quick hack hastily assembled from some Dutch porn site by a couple of students. The last time I gave it a cleanup I've learned more than I asked for, despite considering myself a pretty open and educated person...

So, thanks for filtering the filter. 

I would still suggest leaving all the "teen"-related words in the filter. Losing TMNT and Teen Moms is a relatively small price for filtering out all the stuff that typically hides behind the term...

2021-08-15 08:02 UTC, ichorid commented
Also, please look at #1052

2021-08-16 02:39 UTC, ichorid commented on src/tribler-core/tribler_core/modules/category_filter/filter_terms.filter
> -teen
Please keep this word an other words with the same stem

2021-08-16 02:41 UTC, ichorid requested changes
Please keep the `teen` words in

2021-08-16 03:31 UTC, da2x commented
I’ll put it back in if you insist, but I still believe it’s wrong to filter out Teenage Mutant Ninja Turtles and Teen Vouge just because people sexualize teenagers.

2021-08-16 03:52 UTC, ichorid commented
Don't worry, people would still be able to search for Teen Vogue - they'll
have to enable showing "unsafe" content though.

пн, 16 авг. 2021 г., 06:31 Daniel Aleksandersen ***@***.***>:

> I’ll put it back in if you insist, but I still believe it’s wrong to
> filter out Teenage Mutant Ninja Turtles and Teen Vouge just because people
> sexualize teenagers.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Tribler/tribler/pull/6259#issuecomment-899188453>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AATESL6TSZFZHZVY4BJT5OLT5CBAHANCNFSM5CDZLQFQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-24 13:40 UTC, ichorid approved these changes

2021-08-24 13:47 UTC, merged