Set exit node cache path on Tunnel community
Tribler/tribler pull request #6318
Opened 2021-09-16 15:03 UTC by xoriole

Exit node cache path is not currently set on initialization of the Tunnel Community because of which the cache is not saved during shutdown

2021-09-16 15:11 UTC, xoriole commented
retest this please

2021-09-16 15:43 UTC, ichorid requested changes

2021-09-16 15:43 UTC, ichorid commented on src/tribler-core/tribler_core/components/implementation/tunnels.py
> +        exitnode_cache = Path(config.state_dir) / "exitnode_cache.dat"
Forcing `config.state_dir` to `Path` is unnecessary: `TriblerConfig` object ensures the thing is always a `Path`.

2021-09-17 10:58 UTC, ichorid approved these changes

2021-09-17 11:05 UTC, merged