Add Faker and sentry as common dependency
Tribler/tribler pull request #6656
Opened 2021-12-15 08:52 UTC by xoriole

Fixes https://github.com/Tribler/tribler/issues/6655

Additional to `faker`, `sentry-sdk` is required.

Tested buid here: https://jenkins-ci.tribler.org/job/pers/job/TRIBLER-PR-JOBS/job/PR_build_docs/9/

2021-12-15 13:29 UTC, drew2a commented
Nice! To keep the integrity of `test_dependencies.py` we need to revert this line:
  https://github.com/Tribler/tribler/commit/9427d271308f6513a5710087d89188b58586aaab#diff-c4e1e86fbbab8a03655c675cee5ea28fc87db3b7132cec38fe074480b2a10274L40

Or in another word, we should add the following line to the L40 of `test_dependencies.py`

```python
assert list(get_dependencies(Scope.common))
```

2021-12-16 11:27 UTC, drew2a requested changes
The requested line is still not added :)

2021-12-20 10:16 UTC, kozlovsky approved these changes

2021-12-20 10:20 UTC, xoriole commented
@drew2a Requested changes are applied

> Nice! To keep the integrity of `test_dependencies.py` we need to revert this line: [9427d27#diff-c4e1e86fbbab8a03655c675cee5ea28fc87db3b7132cec38fe074480b2a10274L40](https://github.com/Tribler/tribler/commit/9427d271308f6513a5710087d89188b58586aaab#diff-c4e1e86fbbab8a03655c675cee5ea28fc87db3b7132cec38fe074480b2a10274L40)
> 
> Or in another word, we should add the following line to the L40 of `test_dependencies.py`
> 
> ```python
> assert list(get_dependencies(Scope.common))
> ```

2021-12-20 10:21 UTC, merged