Fix/6700
Tribler/tribler pull request #6738
Opened 2022-01-20 12:08 UTC by drew2a

This PR fixes #6700

During the PR the following bugs were fixed:
1. `import encodings.idna` removes by IDE as unused
2. SentryStrategy.SEND_SUPPRESSED has been set for the core from GUI application

2022-01-21 08:25 UTC, kozlovsky requested changes
Great finding, but it seems that the fix is incomplete. When I launch `run_tribler.py`  with a torrent path as an argument and the torrent name contains URI-encoded characters, Tribler still cannot download the torrent. For example, if I try to download the file `ubuntu%2021.10-desktop-amd64.iso.torrent` (note a `%20` sequence which represents a space character), I see the following error after Tribler is started:

![image](https://user-images.githubusercontent.com/2931136/150491849-36a25b2b-5d2c-46af-aa78-b9a4fcf00db2.png)

As the bug is related to URI-escaped characters, I think it is better to add a test with a torrent file name that contains such characters.

2022-01-21 14:30 UTC, drew2a commented
retest this please

2022-01-21 14:44 UTC, drew2a commented
retest this please

2022-01-21 15:46 UTC, drew2a commented
retest this please

2022-01-21 15:58 UTC, drew2a commented
Our tests use `yarl 1.4.2` But we need at least `yarn 1.6.3` because of https://github.com/aio-libs/yarl/issues/517

![image](https://user-images.githubusercontent.com/13798583/150558423-f1e987bc-6eb5-4a7a-9a40-b1cd45d5c391.png)

2022-01-21 20:29 UTC, drew2a commented
retest this please

2022-01-24 15:54 UTC, kozlovsky approved these changes

2022-01-24 16:25 UTC, kozlovsky approved these changes

2022-01-24 16:25 UTC, merged