Refactoring the folders structure
Tribler/tribler pull request #6803
Opened 2022-03-09 11:07 UTC by drew2a

This PR implements folders' restructuration that was described in #6505

2022-03-11 10:08 UTC, drew2a commented
retest this please

2022-03-11 10:53 UTC, drew2a commented
retest this please

2022-03-11 11:08 UTC, drew2a commented
retest this please

2022-03-11 11:23 UTC, drew2a commented
retest this please

2022-03-11 12:27 UTC, drew2a commented
retest this please

2022-03-11 12:33 UTC, drew2a commented
retest this please

2022-03-11 14:52 UTC, drew2a commented
retest this please

2022-03-11 16:25 UTC, drew2a commented
retest this please

2022-03-14 09:29 UTC, kozlovsky requested changes
Great work!

There are places where `pyipv8` references should be removed as well (remnants from #6757). I cannot specify them in the review, as these files were moved without change and the diff is unavailable, but you can find them with "pyipv8" search. I mean `src/tribler/core/__init__.py` and six examples in the `srcipts` folder. In these lines, `tribler-core` is also mentioned and should be removed, so logically this fix belongs to the current PR.

2022-03-14 09:29 UTC, kozlovsky commented on scripts/exit_node/README.md
> +* Export the `src` directory to to the `PYTHONPATH`
Typo
```suggestion
* Export the `src` directory to `PYTHONPATH`
```

2022-03-14 09:29 UTC, kozlovsky commented on src/README.md
> +Export the `src` directory to to the `PYTHONPATH`:
Typo
```suggestion
Export the `src` directory to `PYTHONPATH`
```

2022-03-14 12:05 UTC, kozlovsky requested changes

2022-03-14 12:05 UTC, kozlovsky commented on src/tribler/gui/upgrade_manager.py
>          # We import it here because it is safer to do it in the main thread
The comment should be deleted as well
```suggestion
```

2022-03-14 12:16 UTC, kozlovsky approved these changes

2022-03-14 13:13 UTC, merged