Add core stdout breadcrumb
Tribler/tribler pull request #7022
Opened 2022-08-29 14:12 UTC by drew2a

This PR adds core stdout breadcrumb.

2022-08-30 10:29 UTC, kozlovsky requested changes
Thanks for the PR! In my opinion, two things need to be fixed:
1. I think we should not add Core stdout output to breadcrumbs, as it contains INFO-level logs that are very spammy and will flood the sentry report with unimportant info. As a result, useful GUI-related breadcrumbs will be cut off, as we limit the number of breadcrumbs added to the report. Instead, we should add `last_core_stderr_output`, which is handled in the `on_core_stderr_read_ready` function below. If Core generates an exception, it will be in stderr.
2. The level for some log messages should be changed from `ERROR` to probably `WARNING` for two reasons:
    1. They do not contain a "real" error relevant to the crash we want to report via Sentry. Usually, we ignore them, disregarding the current `ERROR` level of messages.
    2. They potentially contain sensitive information.
    Specifically, I'm talking about the `on_tracker_error_alert` handler that sends an ERROR-level message to logs. It shows torrent names in breadcrumbs, which is not good for privacy. I think we should change the level of this log message to `WARNING`.

2022-09-01 12:41 UTC, drew2a commented
> I think we should not add Core stdout output to breadcrumbs, as it contains INFO-level logs that are very spammy and will flood the sentry report with unimportant info. As a result, useful GUI-related breadcrumbs will be cut off, as we limit the number of breadcrumbs added to the report. Instead, we should add last_core_stderr_output, which is handled in the on_core_stderr_read_ready function below. If Core generates an exception, it will be in stderr.

Well, we already put into breadcrumbs all kinds of spammy messages (info, warning, error) both from the Core and from the GUI:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/13798583/187915804-40562882-fc72-4d9c-ad38-8f0ce3826d41.png">

2022-09-01 12:45 UTC, drew2a commented
> The level for some log messages should be changed from ERROR to probably WARNING for two reasons:

Maybe, but it is not a part of the current PR. 
This PR is dedicated to adding breadcrumbs from the Core stdout.

2022-09-06 03:21 UTC, kozlovsky approved these changes

2022-09-06 08:39 UTC, merged