Modernized the ReadTheDocs configuration
Tribler/tribler pull request #7640
Opened 2023-10-20 14:53 UTC by qstokkink

Fixes #7636

The current legacy config is no longer supported (see also https://docs.readthedocs.io/en/stable/config-file/v2.html#legacy-build-specification).

2023-10-20 15:01 UTC, drew2a requested changes
Great fix! Please add a newline at the end of `.readthedocs.yml`, and then we can merge this PR.

2023-10-21 07:32 UTC, qstokkink commented
> Great fix! Please add a newline at the end of `.readthedocs.yml`, and then we can merge this PR.

Thank you for your positivity toward this PR. However, your change request is not related to the proposed changes of this PR.

This PR only fixes #7636 and not miscellaneous pre-existing problems with the Tribler codebase, such as a lack of newlines at the end of files. If that is an issue you wish to be solved, please open an issue and it can be resolved in a corresponding PR (i.e., not this PR).

On a more general note. If reviewers are allowed to request arbitrary issues to be fixed in unrelated PRs, it can become impossible to contribute to Tribler. Reviewers could then block any PR indefinitely as there is always another problem. You are currently engaging in this behavior.

Assuming you are not trying to scare away other developers from Tribler, please revise your review. If this is truly your intention, please let me know and I will stop contributing to this repository.

2023-10-23 07:40 UTC, drew2a approved these changes
Yes, indeed this PR addresses the described issue. In this PR, I noticed a flaw in the yml file (which isn't related to the proposed changes) that's quite easy to fix. There's no need to create any new issues for this, as adding a single line is much simpler than creating a new issue. Typically, we rectify such matters immediately since it doesn't demand significant effort from the developer. We've requested such changes in the past from both core Tribler developers and external contributors. Up to this point, everyone has been in agreement and has successfully contributed to the Tribler codebase.

However, if the requested fix is indeed excessive, we can address it in another PR :)

2023-10-23 08:32 UTC, qstokkink commented
Thank you for the revision of your review.

I would like to request reviews of my future PRs to also restrict themselves to the changes made in the PR: this greatly improves my development speed. I appreciate your understanding in this matter.

2023-10-23 08:32 UTC, merged