Add a way to hide columns in the download table
Tribler/tribler pull request #8025
Opened 2024-05-11 17:47 UTC by heldersepu

This PR adds a simple way to hide columns in the download table
double clicking in the header `header().sectionDoubleClicked,` will hide the column `header().hideSection(index)`

2024-05-13 09:51 UTC, kozlovsky requested changes
Thank you for the PR. While hiding a column can be useful for some users, the way it is implemented has some usability issues:

* **Unexpected Behavior:** Double-clicking a column header typically relates to sorting or adjusting the width of the column in many applications. Hiding a column by double-clicking could be counterintuitive for users accustomed to standard UI patterns.

* **Accidental Clicks:** Users might accidentally double-click a header, expecting it to sort or adjust, and instead find the column has disappeared. Imagine the Name column disappears after a user accidentally double-clicks it. This could lead to confusion and frustration. It may be hard for a user to understand what has just happened, and it will look like a bug.

* **Lack of Reversibility:** The absence of an immediate way to bring back the hidden column without restarting the application is a significant usability issue. Users should have the ability to easily undo the action, ideally through the same interface mechanism used to hide it (e.g., right-click the context menu to show/hide columns).

A more intuitive approach might be to implement a right-click context menu on the column headers. This would not only prevent accidental hiding but also enhance functionality by giving users more control.

2024-05-14 12:44 UTC, heldersepu commented
@kozlovsky right-click context menu added

2024-05-15 10:09 UTC, kozlovsky requested changes
It looks good, but one fix should be added.

After you apply the fix, can you please squash all commits in the PR branch to make the commit history easier to read?

2024-05-15 10:09 UTC, kozlovsky commented on src/tribler/gui/widgets/downloadspage.py
> +    def show_all_headers(self):
Currently, when I click on "Restore all", I get the following error:
```python
  File "C:\dev\tribler\src\run_tribler.py", line 126, in <module>
    main()
  File "C:\dev\tribler\src\run_tribler.py", line 122, in main
    run_gui(api_port, api_key, root_state_dir, parsed_args)
  File "C:\dev\tribler\src\tribler\gui\start_gui.py", line 89, in run_gui
    exit_code = app.exec_()
  File "C:\dev\tribler\src\tribler\gui\utilities.py", line 463, in trackback_wrapper
    callback(*args, **kwargs)
  File "C:\dev\tribler\src\tribler\gui\widgets\downloadspage.py", line 571, in on_header_right_click_item
    connect(restore_action.triggered, self.show_all_headers)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\dev\tribler\src\tribler\gui\utilities.py", line 466, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "C:\dev\tribler\src\tribler\gui\utilities.py", line 463, in trackback_wrapper
    callback(*args, **kwargs)
TypeError: show_all_headers() takes 1 positional argument but 2 were given
```

To fix it, you need to specify the second unused argument for the signal handler:
```suggestion
    def show_all_headers(self, _=None):
```

2024-05-15 13:08 UTC, heldersepu commented
> After you apply the fix, can you please squash all commits in the PR branch to make the commit history easier to read?

Fix applied, and all commits have been squashed

2024-05-15 13:31 UTC, kozlovsky approved these changes
Great, thank you for the contribution!

2024-05-15 13:41 UTC, merged